README.org, pkgs.nix
We've pulled in the `stackage.nix` dependency only to use the `mkPkgSet`, as that was moved into `haskell.nix` we don't need to depend on `stackage.nix` anymore.
=> No stackage dependency

stack2nix/Main.hs
This adds support to `nix-tools` to deal with `snapshot.yaml` logic. It's not very clean.
=> stack snapshots

pkgs.nix
Depends on https://github.com/angerman/haskell.nix/pull/4. Once that's merged, I should update the revision of haskell.nix before merging this.
=> Use module system in haskell.nix

default.nix
Helps people like me who don't read the instructions carefully.
Otherwise the build error is really difficult.
=> default.nix: Add check that hackage-db submodule is initialized

default.nix, pkgs.nix
The Hackage Nix expressions will come from `haskell.nix` as of input-output-hk/haskell.nix#47.
=> Import hackage package set from haskell.nix

stack2nix/Stack2nix/Stack.hs
I was added 1.5 years ago in https://github.com/commercialhaskell/stack/commit/cc92bd6b181ef59c595cc16bc152118e64c7f18c but somehow it didn't appear in Stack's changelog or documentation
=> Allow traling file size after revision SHA256 for Stack deps

stack2nix/Stack2nix/Stack.hs
The current output from `stack-to-nix` isn't correct and this fixes it
=> Use revisions with prefix "r" as hackage.nix does

stack2nix/Stack2nix.hs
Fixes https://github.com/input-output-hk/haskell.nix/issues/71
It would help to have tests to catch cases like this.
=> Remove unnecessary .. in src

stack2nix/Stack2nix.hs
PR #32 was actually broken (probably side effect of switching between branches)
This fixes it
=> Fix source lines order broken in 38a0222

stack2nix/Stack2nix.hs, stack2nix/Stack2nix/CLI.hs, stack2nix/Stack2nix/Project.hs
This more or less follows feature I added to cabal2nix in https://github.com/NixOS/cabal2nix/pull/403 - sometimes package comes with a `package.yaml` even from Hackage but we don't want to run `hpack` on it and just use what cabal file contains
=> Option to ignore package.yaml

stack2nix/Stack2nix/Stack.hs
`packages` is optional in `stack.yaml` but if I try `stack-to-nix` on such a project I get a failure:
```
stack-to-nix: nix/pkgs.nix: openFile: does not exist (No such file or directory)
```
=> Use root package by default for Stack

default.nix, nix/.plan-pkgs.nix
There was still some breakage due to `overlay` → `extras`. The haskell.nix revision needed to be updated.
I removed the `overrideWith` because it's not necessary here. The haskell lib can be overridden with normal function args.
=> Fix build and import haskell.nix override

lib/Cabal2Nix.hs, lib/Cabal2Nix/Util.hs
This way in the common case where a dependency is not present we will
give a better error than "attribute missing".
This will bloat the size of the generated files a bit since a lot of the
messages are repeated, but I couldn't see a nice way to do it otherwise
while keeping the `ToNixExpr` functions self-contained.
I was a little bit unsure about `ExeDependency` - I *think* it's trying
to look in `components.exes` although at the moment it just looks at the
ambient scope. I made this explicit.
=> Give better error messages when dependencies are not present

plan2nix/Plan2Nix.hs, stack2nix/Stack2nix.hs
See https://github.com/input-output-hk/haskell.nix/issues/254
=> Use mkOverride 900 for project flags.

stack2nix/Stack2nix.hs, stack2nix/Stack2nix/External/Resolve.hs
Supersedes input-output-hk/haskell.nix#338 (see it for test).
=> Resolve local file snapshots relative to stack.yaml

hackage2nix/Main.hs, nix-tools.cabal
This decreases hackage.nix loading time by approximately 5x (from 1.6s to 0.3s),
dropping my evaluation time from 8s to 6s in total (todo: is hackage.nix imported multiple times somehow?). It would be nicer to keep the old mode of operation intact, but this will be hard without a lot of code duplication.
=> hackage2nix: switch to json output

lts2nix/Main.hs
As described in https://github.com/input-output-hk/haskell.nix/issues/481, the import logic for the new Stackage format does not include the "compiler packages" as provided by the snapshot. This PR fixes that logic by including those packages with their default revisions.
=> Add compiler packages to list of packages in Stackage LTS

cabal2nix/Main.hs, lib/Stack2nix/Project.hs, plan2nix/Plan2Nix/Project.hs
When you run hpack from the command line, it puts `cabal-version` into generated cabal file, in addition to the result of `renderPackage` function. This field defines which features the cabal file may use, and may also affect parsing. For example, parsing of the `license` field depends on `cabal-version`: https://github.com/haskell/cabal/pull/5050, so without it cabal will fail to parse generated file for a `package.yaml` like this:
```yaml
name: example
version: 1
license: LicenseRef-Custom
library:
dependencies:
- base
```
This PR makes sure this field is included when hpack is used
=> Include cabal-version field into cabal files generated with hpack

.buildkite/build.sh, .buildkite/fixed.nix, cabal.project, default.nix, hackage2nix/Main.hs, lib/Cabal2Nix.hs, lib/Stack2nix.hs, lib/Stack2nix/Stack.hs, lts2nix/Main.hs, nix-tools.cabal, plan2nix/Plan2Nix.hs, shell.nix
We'll need to support Cabal-3.2 to that hackage.nix properly updated, and we can parse `.cabal` files using new cabal features/formats. This requires to upgrade `nix-tools` to build against the `Cabal-3.2`.
=> Cabal 3.2 support

.buildkite/build.sh, default.nix, lib/Cabal2Nix.hs
to save some disk space: ~30% uncompressed, ~15% compressed.
Should also ease maintenance of those functions.
Sister PR: https://github.com/input-output-hk/haskell.nix/pull/588
Btw, is there any point to pushing the hackage index (`index.tar.gz` ~ 85Mo) to the hackage.nix repo?
=> externalize errors msg functions to hsPkgs provided by haskell.nix

cabal.project, default.nix
When updating hackage-db cabal-revisions branch [this append](https://github.com/peti/hackage-db/pull/9/files#diff-7968cd26685b48210552ee1d525cfec0R87) was left out. It is added [here](https://github.com/hamishmack/hackage-db/commit/3f12730c0d6092efce142cad87264e7b7eb2b05a) and this PR updates nix-tools.
=> Fix hackage-to-nix missing old hackage revisions

lib/Stack2nix/Stack.hs
Previously the commutative [`(+++)`](https://hackage.haskell.org/package/Cabal-2.4.1.0/docs/Distribution-Compat-ReadP.html#v:-43--43--43-) operator was used, but with e04dbd4ea7cb7eeb00acdbe4d4e1b7b66dcb19d7 the [`(<|>)`](https://hackage.haskell.org/package/Cabal-3.2.0.0/docs/Distribution-Compat-Prelude-Internal.html#v:-60--124--62-) operator is used instead, which is only associative, but not commutative for the parser used.
This PR fixes this with a [`try`](https://hackage.haskell.org/package/Cabal-3.2.0.0/docs/Distribution-Compat-Parsing.html#v:try) on the first branch, such that the second one gets used if the first one fails (with backtracking).
A better fix would be possible with something like `char '@' *> some (satisfy isAlpha) <* char ':'` and deciding the branch based on the …
=> Fix `@rev:<n>` extra-deps specification not working

plan2nix/Plan2Nix.hs
They are no longer always local:
https://github.com/haskell/cabal/commit/2b6cd51a9638dec56cf8c70fafcdd20ab53d5714
https://github.com/haskell/cabal/issues/5586
=> Fix source-repo under Cabal 3.4 generated plans

lib/Cabal2Nix.hs, nix-tools.cabal
This change uses the same logic that cabal-install uses for determining the path of a packages `.tar.gz` in a repository.
=> Use cabal-install logic for package tar.gz uri
